services:
  aniphim:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: aniphim
    restart: unless-stopped
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3002
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3002
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
